name: kec_biomat
channels: [conda-forge, pytorch]
dependencies:
  - python=3.11
  - numpy
  - scipy
  - networkx
  - scikit-image
  - scikit-learn
  - pandas
  - matplotlib
  - pip
  - pip:
      - porespy
      - openpnm
      - GraphRicciCurvature
      - torch
      - torch-geometric
