# Build direto do frontend DARWIN
timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.production'
  - '-t'
  - 'gcr.io/pcs-helio/darwin-frontend:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/pcs-helio/darwin-frontend:latest'

images:
- 'gcr.io/pcs-helio/darwin-frontend:latest'
