openapi: 3.1.0
info:
  title: DARWIN Research API
  version: "1.0.0"
  description: |
    DARWIN Mode B Cloud API exposing retrieval-augmented endpoints for biomaterials research.
servers:
- url: https://darwin-rag-862291807500.us-central1.run.app
  description: Cloud Run deployment
paths:
  /rag-plus/search:
    post:
      summary: Search knowledge base via RAG+
      security:
      - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: Natural language question.
                k:
                  type: integer
                  description: Maximum number of passages.
                  default: 4
              required: [ q ]
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        doc_id:
                          type: string
                        score:
                          type: number
                        metadata:
                          type: object
  /discovery/run:
    post:
      summary: Trigger discovery ingest job
      security:
      - ApiKeyAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                run_once:
                  type: boolean
      responses:
        "200":
          description: Ingest summary
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
