# DARWIN Backend Build - Simple Version
# Foco apenas no build da imagem, sem deploy

timeout: 1800s

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: 'pcs-helio'
  _REGION: 'us-central1'
  _IMAGE_NAME: 'gcr.io/pcs-helio/darwin-backend'
  _DOCKERFILE_PATH: './Dockerfile.production'

steps:
# Environment Validation
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'validate-environment'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "🔍 Validating build environment..."
    echo "Project ID: ${_PROJECT_ID}"
    echo "Image Name: ${_IMAGE_NAME}"
    echo "Dockerfile: ${_DOCKERFILE_PATH}"
    echo "✅ Environment validation completed"

# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  args:
  - 'build'
  - '--file=${_DOCKERFILE_PATH}'
  - '--tag=${_IMAGE_NAME}:${SHORT_SHA}'
  - '--tag=${_IMAGE_NAME}:latest'
  - '--build-arg=ENVIRONMENT=production'
  - '--build-arg=BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
  - '--build-arg=VCS_REF=${SHORT_SHA}'
  - '.'
  waitFor: [ 'validate-environment' ]

# Push Images
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-image-sha'
  args:
  - 'push'
  - '${_IMAGE_NAME}:${SHORT_SHA}'
  waitFor: [ 'build-image' ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-image-latest'
  args:
  - 'push'
  - '${_IMAGE_NAME}:latest'
  waitFor: [ 'build-image' ]

# Final Summary
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'build-summary'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "🎉 DARWIN Backend Build Completed!"
    echo ""
    echo "📋 Build Summary:"
    echo "• Project: ${_PROJECT_ID}"
    echo "• Image SHA: ${_IMAGE_NAME}:${SHORT_SHA}"
    echo "• Image Latest: ${_IMAGE_NAME}:latest"
    echo "• Build Time: $(date)"
    echo ""
    echo "✅ Images ready for deployment!"
  waitFor: [ 'push-image-sha', 'push-image-latest' ]

images:
- '${_IMAGE_NAME}:${SHORT_SHA}'
- '${_IMAGE_NAME}:latest'
