# KEC 2.0 — Configuração padrão (pode ser versionada por experimento)
seed: 42

segmentation:
  method: "otsu_local"
  bilateral_filter: true
  bilateral_sigma_color: 75
  bilateral_sigma_space: 75
  cnn_proxy: false        # true ativa CNN por patches (opcional)

graph_extraction:
  use_porespy: true
  throat_weights: ["diameter", "length", "conductance_proxy"]

entropy:
  method: "spectral"      # "spectral" (von Neumann) | "shannon_walk" (baseline)
  k_eigs: 64
  tol: 1e-8
  stochastic_trace: false # fallback automático quando mem.limit

curvature:
  forman:
    enabled: true
    include_triangles: true
  ollivier:
    enabled: true
    method: "sinkhorn"
    sample_frac: 0.2      # amostra de arestas para estatísticas globais
    sinkhorn_eps: 0.01
    n_iter: 100

coherence:
  sigma_small_world: true
  swp: true
  n_random: 20            # redes aleatórias p/ normalização
  sigma_Q: false          # coerência “quântica” opcional

modeling:
  baseline: "random_forest"
  gnn:
    enabled: true
    embedding_mode: true  # se true: usa GNN para gerar embedding + RF
    layers: 3
    hidden_dim: 64
    dropout: 0.3

reporting:
  null_models: true
  preserve_degree_nulls: 100
  ci_bootstrap: 1000
