# CLOUD RUN CONFIGURATION - DARWIN Revolutionary Setup
# Advanced Cloud Run configuration with GPU/TPU capability for DARWIN
# 🚀 CLOUD RUN REVOLUTIONARY CONFIGURATION

# ============================================================================
# Service Configuration - Main DARWIN Backend
# ============================================================================
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: darwin-backend
  namespace: default
  labels:
    cloud.googleapis.com/load-balancer-type: "External"
    app: darwin-backend
    component: ai-research
    framework: autogen-jax
    acceleration: gpu-ready
  annotations:
    # Cloud Run specific annotations
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "20"
    run.googleapis.com/cpu-throttling: "false"
    run.googleapis.com/execution-environment: gen2

    # GPU annotations (when available)
    run.googleapis.com/gpu-type: "nvidia-tesla-t4"
    run.googleapis.com/gpu-count: "1"

spec:
  template:
    metadata:
      labels:
        app: darwin-backend
        version: v3-production
      annotations:
        # Scaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "20"
        autoscaling.knative.dev/target: "70"

        # Performance optimization
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: "darwin-vpc-connector"

        # Memory and CPU optimization
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/cpu: "2"

    spec:
      # Container configuration
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: vertex-ai-darwin-main@darwin-biomaterials-scaffolds.iam.gserviceaccount.com

      containers:
      - name: darwin-backend
        image: gcr.io/darwin-biomaterials-scaffolds/darwin-backend:latest

        # Resource allocation
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
            # GPU limits (when available)
            nvidia.com/gpu: "1"
          requests:
            cpu: "1000m"
            memory: "2Gi"

        # Port configuration
        ports:
        - name: http1
          containerPort: 8080
          protocol: TCP
        # Environment variables
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "8080"
        - name: WORKERS
          value: "1"
        - name: GOOGLE_CLOUD_PROJECT
          value: "darwin-biomaterials-scaffolds"
        - name: GCP_LOCATION
          value: "us-central1"

        # DARWIN feature flags
        - name: ENABLE_AUTOGEN_RESEARCH_TEAM
          value: "true"
        - name: ENABLE_JAX_ULTRA_PERFORMANCE
          value: "true"
        - name: ENABLE_VERTEX_AI_INTEGRATION
          value: "true"
        - name: ENABLE_BIGQUERY_PIPELINE
          value: "true"
        - name: ENABLE_CUSTOM_MODELS
          value: "true"
        - name: ENABLE_REAL_TIME_ANALYTICS
          value: "true"

        # JAX GPU configuration
        - name: JAX_PLATFORM_NAME
          value: "gpu"
        - name: CUDA_VISIBLE_DEVICES
          value: "all"
        - name: XLA_PYTHON_CLIENT_PREALLOCATE
          value: "false"
        - name: XLA_PYTHON_CLIENT_ALLOCATOR
          value: "platform"

        # Performance optimization
        - name: OMP_NUM_THREADS
          value: "4"
        - name: MALLOC_TRIM_THRESHOLD
          value: "131072"
        # Health check configuration
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
# ============================================================================
# Service Configuration - DARWIN GPU High-Performance Backend
# ============================================================================
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: darwin-backend-gpu
  namespace: default
  labels:
    cloud.googleapis.com/load-balancer-type: "External"
    app: darwin-backend-gpu
    component: ai-research-gpu
    framework: autogen-jax-cuda
    acceleration: gpu-accelerated
  annotations:
    run.googleapis.com/ingress: all
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "5"
    run.googleapis.com/cpu-throttling: "false"
    run.googleapis.com/execution-environment: gen2

spec:
  template:
    metadata:
      labels:
        app: darwin-backend-gpu
        version: v3-gpu
      annotations:
        # GPU-specific scaling
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "50"

        # High-performance configuration
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: "darwin-vpc-connector"

    spec:
      # GPU container configuration
      containerConcurrency: 10 # Lower concurrency for GPU workloads
      timeoutSeconds: 600 # Longer timeout for complex computations
      serviceAccountName: vertex-ai-darwin-main@darwin-biomaterials-scaffolds.iam.gserviceaccount.com

      containers:
      - name: darwin-backend-gpu
        image: gcr.io/darwin-biomaterials-scaffolds/darwin-backend-gpu:latest

        # GPU resource allocation
        resources:
          limits:
            cpu: "4000m"
            memory: "8Gi"
            nvidia.com/gpu: "1"
          requests:
            cpu: "2000m"
            memory: "4Gi"
            nvidia.com/gpu: "1"

        ports:
        - name: http1
          containerPort: 8080
        # GPU-optimized environment
        env:
        - name: ENVIRONMENT
          value: "production-gpu"
        - name: PORT
          value: "8080"
        - name: WORKERS
          value: "1"
        - name: GOOGLE_CLOUD_PROJECT
          value: "darwin-biomaterials-scaffolds"

        # GPU acceleration settings
        - name: JAX_PLATFORM_NAME
          value: "gpu"
        - name: CUDA_VISIBLE_DEVICES
          value: "all"
        - name: XLA_PYTHON_CLIENT_PREALLOCATE
          value: "false"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"

        # Performance tuning for GPU
        - name: TF_FORCE_GPU_ALLOW_GROWTH
          value: "true"
        - name: XLA_FLAGS
          value: "--xla_gpu_cuda_data_dir=/usr/local/cuda"
        # Enhanced health checks for GPU workloads
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 180 # Longer for GPU initialization
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
---
# ============================================================================
# Load Balancer Configuration
# ============================================================================
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: darwin-backend-ssl
spec:
  domains:
  - api.darwin-research.cloud
  - backend.darwin-research.cloud
---
apiVersion: v1
kind: Service
metadata:
  name: darwin-backend-lb
  labels:
    app: darwin-backend
spec:
  type: LoadBalancer
  loadBalancerClass: gce
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: darwin-backend
---
# ============================================================================
# Horizontal Pod Autoscaler (HPA)
# ============================================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: darwin-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: darwin-backend
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
---
# ============================================================================
# TPU Configuration (Cloud Run Jobs for TPU workloads)
# ============================================================================
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: darwin-tpu-processing
  labels:
    app: darwin-tpu
    component: ultra-performance
spec:
  template:
    spec:
      template:
        spec:
          restartPolicy: Never
          taskCount: 1
          parallelism: 1
          taskTimeoutSeconds: 3600
          serviceAccountName: vertex-ai-darwin-main@darwin-biomaterials-scaffolds.iam.gserviceaccount.com

          containers:
          - name: darwin-tpu-worker
            image: gcr.io/darwin-biomaterials-scaffolds/darwin-backend-gpu:latest

            # TPU resource allocation
            resources:
              limits:
                google.com/tpu: "1"
                cpu: "8000m"
                memory: "16Gi"
              requests:
                google.com/tpu: "1"
                cpu: "4000m"
                memory: "8Gi"

            env:
            - name: JAX_PLATFORM_NAME
              value: "tpu"
            - name: TPU_NAME
              value: "darwin-tpu-v3"
            - name: ENVIRONMENT
              value: "production-tpu"
            - name: ENABLE_TPU_ACCELERATION
              value: "true"
            # Command for TPU processing
            command: [ "python" ]
            args: [ "-m", "kec_unified_api.performance.tpu_benchmark" ]
---
# ============================================================================
# Network Configuration
# ============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: darwin-network-config
data:
  vpc-connector: "darwin-vpc-connector"
  subnet: "darwin-subnet"
  region: "us-central1"

  # Load balancing configuration
  lb-scheme: "EXTERNAL"
  lb-type: "HTTPS"

  # CDN configuration
  cdn-enabled: "true"
  cdn-cache-ttl: "3600"

  # Security configuration
  ssl-policy: "modern-tls"
  enable-iap: "false"
---
# ============================================================================
# Monitoring Configuration
# ============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: darwin-monitoring-config
data:
  # Prometheus monitoring
  prometheus-enabled: "true"
  prometheus-port: "9090"

  # Custom metrics
  custom-metrics: |
    - jax_compilation_time
    - autogen_collaboration_count
    - vertex_ai_request_latency
    - bigquery_insert_rate
    - scaffold_processing_throughput
    - gpu_utilization_percent
    - memory_usage_percent

  # Alert thresholds
  alert-cpu-threshold: "80"
  alert-memory-threshold: "85"
  alert-error-rate-threshold: "5"
  alert-latency-threshold: "2000"

  # Dashboard configuration
  grafana-enabled: "true"
  cloud-monitoring-enabled: "true"
---
# ============================================================================
# Security Configuration  
# ============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: darwin-backend-secrets
type: Opaque
stringData:
  # Database connections
  database-url: ""
  redis-url: ""

  # API keys (will be populated from Secret Manager)
  openai-api-key: ""
  anthropic-api-key: ""
  google-api-key: ""

  # Service account keys (mounted from Secret Manager)
  vertex-ai-key: ""
  bigquery-key: ""
---
# ============================================================================
# Storage Configuration
# ============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: darwin-storage-config
data:
  # Google Cloud Storage
  gcs-bucket-training: "darwin-training-data-darwin-biomaterials-scaffolds"
  gcs-bucket-artifacts: "darwin-model-artifacts-darwin-biomaterials-scaffolds"
  gcs-bucket-logs: "darwin-experiment-logs-darwin-biomaterials-scaffolds"

  # BigQuery datasets
  bq-dataset-insights: "darwin_research_insights"
  bq-dataset-metrics: "darwin_performance_metrics"
  bq-dataset-results: "darwin_scaffold_results"

  # Cache configuration
  cache-type: "memory"
  cache-ttl: "3600"
  cache-max-size: "1000"
